# Generated by Django 4.2.5 on 2024-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto_perfil',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto_perfil',
            field=models.URLField(blank=True),
        ),
    ]
