# Generated by Django 5.1.2 on 2024-11-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0003_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='meu_app.aluno')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='meu_app.servico')),
            ],
            options={
                'unique_together': {('aluno', 'servico')},
            },
        ),
    ]
